### ISSUE TITLE
Code Review - Aadarsh Patel - graphs.py

### ISSUE THREAD

**Issue by arp97-njit** [AmeerYHassan/CS435-Project-Two#1]
#1
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P3%20-%20Graphs.py#L30
Add a check to make sure the random int you make isn't equal.  It's rare that this will happen, but if it does, you should handle it

#2
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P3%20-%20Graphs.py#L33
What if instead of 2 for loops, you just do 1 loop where you make the node and connect it at the same time? It would cut the time of execution down.
So in the loop, you would have a base case where on the first iteration, you just make a node.  Then on the second iteration(onward) you can add the connection between your current pointer and 1 before.

#3
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P3%20-%20Graphs.py#L41
This is supposed to be in its own GraphSearch class

#4
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P3%20-%20Graphs.py#L66
Instead of using a visited array, why not have a visited value for the node class itself?
That way you would not have to run an inner loop when you check to see if it has been visited already or not.

#5
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P3%20-%20Graphs.py#L103
Same as in comment 4.  If the node itself has that value, you wouldn't need to iterate through the whole array just to remove a node from that unvisited array.  

#6
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P3%20-%20Graphs.py#L120
If you iterate through the nodes in unvisited, you won't have to do the check at line 132.
Also, making visited a boolean part of the node would help in the following, but isn't needed
Lets say there are 2 separate graphs inside your input.
You grab the first unvisted node and make that curr and go through all of its neighbors.
Now that you have visited all the neighbors in the first graph, as you iterate through your unvisited array, you would find a node from that 2nd graph and go through all of it's neighbors using the same code.
Just removed the redundancy at line 132

**Comment by AmeerYHassan** [comment]
#1: This check could be done, but it's legal for a graph to have edges leading into itself, so either way the resulting graph is legal.
#2: I have tried to tackle this problem when I was coding, but I couldn't seem to figure out how to do it without overlapping edges and creating duplicate nodes. Either way, both of the solutions are O(n).
#3:  Addressed in commit: https://github.com/AmeerYHassan/CS435-Project-Two/commit/fb723c61eb695de2b5fb7cfe06fdf9f6ded216d7
#4: The reason why I decided not to have a visited attribute is because it would have to be reset each time the method would be run, so at the end of the day you would have to iterate through them all. It's just a conflict of design.
#5: See above
#6: Addressed in commit: https://github.com/AmeerYHassan/CS435-Project-Two/commit/fb723c61eb695de2b5fb7cfe06fdf9f6ded216d7
