### ISSUE TITLE
Code Review - Aadarsh Patel -  Directed Acyclic Graphs.py

### ISSUE THREAD

**Issue by arp97-njit** [AmeerYHassan/CS435-Project-Two#2]
#7
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P4%20-%20Directed%20Acyclic%20Graphs.py#L92
Should use the addDirectedEdge function here.

#8
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P4%20-%20Directed%20Acyclic%20Graphs.py#L92
Along with comment 7, you would want to make sure it is not already a neighbor so you don't add it twice.

#9
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P4%20-%20Directed%20Acyclic%20Graphs.py#L50
No need to pass in the graph here

#10
https://github.com/AmeerYHassan/CS435-Project-Two/blob/master/P4%20-%20Directed%20Acyclic%20Graphs.py#L45
If you have the visited value as part of the node object, you can remove this code since it will already start as false.

**Comment by AmeerYHassan** [comment]
#7: Addressed in the commit: https://github.com/AmeerYHassan/CS435-Project-Two/commit/b0137b8e78e3dc978690b91daae14e8b5b9d478a
#8: Since it's a set, if it adds a neighbor that already exists then nothing will change, so a check isn't necessary.
#9: The graph is passed in in order to iterate through a nodes neighbors.
#10: This is true, but if I were to call it again then I would have to make another function to make all of the visited values false, which just seems like unnecessary work. Just a different design choice.
